// Code generated by MockGen. DO NOT EDIT.
// Source: news-app/internal/parser (interfaces: InternalParser,UniversalParser)

// Package parser is a generated GoMock package.
package parser

import (
	context "context"
	domain "news-app/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gofeed "github.com/mmcdole/gofeed"
)

// MockInternalParser is a mock of InternalParser interface.
type MockInternalParser struct {
	ctrl     *gomock.Controller
	recorder *MockInternalParserMockRecorder
}

// MockInternalParserMockRecorder is the mock recorder for MockInternalParser.
type MockInternalParserMockRecorder struct {
	mock *MockInternalParser
}

// NewMockInternalParser creates a new mock instance.
func NewMockInternalParser(ctrl *gomock.Controller) *MockInternalParser {
	mock := &MockInternalParser{ctrl: ctrl}
	mock.recorder = &MockInternalParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInternalParser) EXPECT() *MockInternalParserMockRecorder {
	return m.recorder
}

// ParseURLWithContext mocks base method.
func (m *MockInternalParser) ParseURLWithContext(arg0 string, arg1 context.Context) (*gofeed.Feed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseURLWithContext", arg0, arg1)
	ret0, _ := ret[0].(*gofeed.Feed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseURLWithContext indicates an expected call of ParseURLWithContext.
func (mr *MockInternalParserMockRecorder) ParseURLWithContext(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseURLWithContext", reflect.TypeOf((*MockInternalParser)(nil).ParseURLWithContext), arg0, arg1)
}

// MockUniversalParser is a mock of UniversalParser interface.
type MockUniversalParser struct {
	ctrl     *gomock.Controller
	recorder *MockUniversalParserMockRecorder
}

// MockUniversalParserMockRecorder is the mock recorder for MockUniversalParser.
type MockUniversalParserMockRecorder struct {
	mock *MockUniversalParser
}

// NewMockUniversalParser creates a new mock instance.
func NewMockUniversalParser(ctrl *gomock.Controller) *MockUniversalParser {
	mock := &MockUniversalParser{ctrl: ctrl}
	mock.recorder = &MockUniversalParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUniversalParser) EXPECT() *MockUniversalParserMockRecorder {
	return m.recorder
}

// Parse mocks base method.
func (m *MockUniversalParser) Parse(arg0 context.Context, arg1 string) (domain.Feed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", arg0, arg1)
	ret0, _ := ret[0].(domain.Feed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockUniversalParserMockRecorder) Parse(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockUniversalParser)(nil).Parse), arg0, arg1)
}
